[package]
name = "server"
version = "0.1.0"
authors = ["gregjhansell97 <gregjhansell@gmail.com>"]
edition = "2018"

[dependencies]
rouille = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
